services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ev_charging_system:latest
    container_name: ev_charging_web
    restart: on-failure
    # Use the simplified command
    command:
      bash -c "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:9000
      "
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    networks:
      - charging_network
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: ev-frontend
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      charging_network:

  redis:
    image: "redis:latest"
    container_name: ev_charging_redis
    hostname: "redis"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - charging_network

networks:
  charging_network:
    driver: bridge