# Generated by Django 4.2.20 on 2025-05-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Charging', '0002_initial'),
        ('Commanding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transaction', to='Users.customer'),
        ),
        migrations.AddField(
            model_name='statuslog',
            name='charger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charger', to='Charging.evcharger'),
        ),
    ]
