# Generated by Django 4.2.20 on 2025-05-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Charging', '0002_initial'),
        ('Commanding', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartbeatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(null=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='Charging.evcharger')),
            ],
        ),
    ]
