# Generated by Django 4.2 on 2025-05-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commanding', '0003_heartbeatlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
