# Generated by Django 4.2.21 on 2025-05-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commanding', '0004_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslog',
            name='payload',
            field=models.JSONField(null=True),
        ),
    ]
