# Generated by Django 4.2.20 on 2025-05-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Charging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='Users.organization'),
        ),
        migrations.AddField(
            model_name='evcharger',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='Charging.station'),
        ),
    ]
