# Generated by Django 4.2.23 on 2025-06-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charging', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcharger',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('preparing', 'Preparing'), ('charging', 'Charging'), ('finishing', 'Finishing')], default='available', max_length=10),
        ),
    ]
