# Generated by Django 4.2.23 on 2025-06-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charging', '0003_alter_evcharger_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcharger',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='evcharger',
            name='connected',
        ),
        migrations.AlterField(
            model_name='evcharger',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('preparing', 'Preparing'), ('charging', 'Charging'), ('SuspendedEVSE', 'SuspendedEVSE'), ('suspendedEV', 'SuspendedEV'), ('reserved', 'Reserved'), ('unavailable', 'Unavailable'), ('faulted', 'Faulted'), ('finishing', 'Finishing')], default='available', max_length=20),
        ),
    ]
